const scenarios = [
 {id:'choice', question:'我已经在现在的公司工作五年了，现在离开是不是太可惜？', answer:['你在权衡的可能不只是要不要离开，而是过去五年的投入，是否意味着未来只能继续。','“可惜”常常把时间、熟悉感和对未知的担心叠在一起。你可以把决定拆成：留下会得到什么，离开想换取什么，以及有没有低成本试探的方式。'], discovery:'这周还有 6 个人，也停在类似的位置。', candidates:{A:{id:'choice-a',path:'A · 处境相近',source:'对方授权分享',time:'两天前授权分享',quote:'我也在一份做了很久的工作里，反复想象离开的那一天。最难的不是不知道外面有什么，而是觉得已经走了这么远。',context:'匿名 · 在熟悉的工作里停留了几年',shared:'你们似乎都在面对“投入很久以后，还能不能重新选择”。',difference:'TA 选择先请了一个月假，试着把离开从一次性决定变成一段试验。',contact:true,name:'一个正在试着转身的人'},B:{id:'choice-b',path:'B · 结构相近',source:'知乎公开回答',time:'三天前发表',quote:'读博第四年，我最常问自己的不是要不要毕业，而是：已经投入这么多以后，改变方向是不是一种失败？',context:'知乎用户 · 公开回答',shared:'你们经历的事情不同，但似乎都在问：过去的投入，能不能成为重新选择的理由。',difference:'TA 面对的是学业路径，而你面对的是工作；答案可能不同，但犹豫的结构很像。',contact:true,name:'一位仍在重新选择的人'}}},
 {id:'square', question:'为什么有些广场让人愿意停下来，有些却只想赶快穿过去？', answer:['你注意到的也许不只是广场的设计，而是一个空间有没有给人留下“可以待一会儿”的理由。','座椅、树荫和人的密度会影响停留，但更重要的是：这里是否允许人以自己的节奏出现，不必马上消费或完成什么。'], discovery:'这周还有 4 个人，也在留意人与公共空间的距离。', candidates:{A:{id:'square-a',path:'A · 兴趣相近',source:'对方授权分享',time:'四天前授权分享',quote:'我会记住那些让人自然慢下来的街角。没有打卡点，但有人坐着，孩子在跑，陌生人也不急着离开。',context:'匿名 · 关注城市空间与日常观察',shared:'你们都在观察，一个地方如何让陌生人愿意共同停留。',difference:'TA 从城市设计出发，而你更在意走过时身体和情绪的感受。',contact:true,name:'一位观察街角的人'},B:{id:'square-b',path:'B · 结构相近',source:'知乎公开评论',time:'昨天发表',quote:'好的游戏空间不是把所有路径都设计好，而是让玩家有机会偏离任务，遇见原本没计划遇见的人。',context:'知乎用户 · 公开评论',shared:'你们似乎都在寻找一种不会催促人的空间：可以停下，也可以走向意外。',difference:'TA 谈的是虚拟世界里的规则，你谈的是现实中的广场；但两者都在讨论自由停留的条件。',contact:false,name:'一位讨论游戏空间的人'}}}
];
let state={screen:'home',scenario:null,stage:0,selected:null,letter:'',invite:'draft',timer:null};
const app=document.querySelector('#app');
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function render(){const s=state.scenario; let html=`<header><span class="logo">未见之人</span><span class="demo">DEMO · 交互原型</span>${state.screen!=='home'?'<button class="reset" data-action="reset">重新开始</button>':''}</header>`;
 if(state.screen==='home') html+=`<main class="home"><p class="eyebrow">AI 帮你走到门口，把相遇留给人</p><h1>看看这周，还有谁也在想与你有关的事情。</h1><p class="hint">从一个最近可能想过的问题开始</p><div class="scenario-grid">${scenarios.map(x=>`<button class="scenario" data-action="start" data-id="${x.id}"><span>开始一次相遇</span><strong>${esc(x.question)}</strong><i>→</i></button>`).join('')}</div><p class="footnote">Demo 暂不支持自由问题 · 内容为演示用 Mock 数据</p></main>`;
 else if(state.screen==='chat') html+=chat(s);
 else if(state.screen==='directions') html+=directions(s);
 else if(state.screen==='card') html+=card(s.candidates[state.selected],state.selected);
 else if(state.screen==='letter') html+=letter(s.candidates[state.selected]);
 else if(state.screen==='invite') html+=invite(s.candidates[state.selected]);
 else html+=privateChat(s.candidates[state.selected]);
 app.innerHTML=html; bind();}
function chat(s){const msgs=[]; for(let i=0;i<state.stage&&i<3;i++){if(i===0)msgs.push(`<div class="msg user">${esc(s.question)}</div>`); else msgs.push(`<div class="msg agent">${esc(s.answer[i-1])}</div>`)} let done=state.stage>=3; return `<main class="conversation"><div class="topic">${esc(s.question)}</div><div class="messages">${msgs.join('')}${state.stage<3?'<div class="typing">Agent 正在认真想…</div>':''}</div>${done?`<div class="discovery"><p>${esc(s.discovery)}</p><h2>想要看看其他人吗？</h2><span>如果你现在不想继续找答案，也可以看看，这周还有谁在想与你有关的事情。</span><div><button class="ghost" data-action="stay">暂时不用</button><button class="primary" data-action="discover">看看</button></div></div>`:''}</main>`}
function directions(s){return `<main class="directions"><p class="eyebrow">发现层</p><h1>我发现了两条<br/>可能与你有关的表达。</h1><div class="direction a"><span>A · 处境相近</span><h2>我知道有一个人，和你的处境非常接近。</h2><button data-action="view" data-id="A">查看 A <b>→</b></button></div><div class="direction b"><span>B · 结构相近</span><h2>但我知道还有另一个人，可能更值得试试。</h2><p>TA 经历的事情和你不同，但我发现，你们似乎都在面对相似的选择。</p><button data-action="view" data-id="B">查看 B <b>→</b></button></div></main>`}
function card(c,key){return `<main class="card-page"><button class="back" data-action="back">← 返回</button><p class="eyebrow">${c.path}</p><div class="quote">“${esc(c.quote)}”</div><p class="source">${esc(c.source)} · ${esc(c.time)} <em>演示数据</em></p><section><label>为什么可能与你有关</label><p>${esc(c.shared)}</p></section><section class="difference"><label>留下一点不同</label><p>${esc(c.difference)}</p></section><p class="identity">${esc(c.context)}</p><div class="actions">${c.contact?`<button class="primary" data-action="write">回应 TA</button>`:''}<button class="ghost" data-action="back">只是看看</button></div></main>`}
function letter(c){return `<main class="letter-page"><button class="back" data-action="back">← 返回表达</button><p class="eyebrow">写给 ${esc(c.name)}</p><h1>现在轮到你，写一句你还没对任何人说过的话。</h1><p>这封信会发给刚才看见的 TA。对方可以接受，也可以不回应。</p><textarea id="letter" placeholder="写下你想对 TA 说的话……">${esc(state.letter)}</textarea><div class="actions"><button class="ghost" data-action="back">取消</button><button class="primary" data-action="send">发送邀请</button></div></main>`}
function invite(c){return `<main class="status-page"><div class="status-icon">✓</div><p class="eyebrow">邀请已发送</p><h1>等 TA 做出选择。</h1><p>你的话已经送给 ${esc(c.name)}。Demo 主路径中，TA 选择了接受。</p><div class="sent-message">“${esc(state.letter)}”</div><button class="primary" data-action="accept">进入私人交流</button><button class="text-btn" data-action="reset">结束这次 Demo</button></main>`}
function privateChat(c){return `<main class="private-page"><p class="eyebrow">私人交流 · ${esc(c.name)}</p><h1>从这里开始，交给你们自己。</h1><div class="private-note">AI 已经退到一旁。接下来没有推荐、没有分析，只有你们愿意说的话。</div><div class="chat-input"><input placeholder="写下你的消息…"/><button class="primary">发送</button></div><button class="text-btn" data-action="reset">重新体验</button></main>`}
function bind(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='start'){state.scenario=scenarios.find(x=>x.id===b.dataset.id);state.screen='chat';state.stage=0;play();} if(a==='discover'){state.screen='directions';render();} if(a==='view'){state.selected=b.dataset.id;state.screen='card';render();} if(a==='write'){state.screen='letter';render();} if(a==='send'){state.letter=document.querySelector('#letter').value.trim();if(!state.letter){document.querySelector('#letter').focus();return;}state.invite='sent';state.screen='invite';render();} if(a==='accept'){state.screen='private';render();} if(a==='back'){state.screen=state.screen==='letter'?'card':state.screen==='card'?'directions':'chat';render();} if(a==='stay'){state.screen='chat';render();} if(a==='reset'){clearTimeout(state.timer);state={screen:'home',scenario:null,stage:0,selected:null,letter:'',invite:'draft',timer:null};render();}});}
function play(){render(); if(state.stage<3){state.timer=setTimeout(()=>{state.stage++;play()},1100);}}
render();
const zhihuLoginButton = document.querySelector('#zhihu-login');
if (zhihuLoginButton) zhihuLoginButton.addEventListener('click', () => {
  window.location.href = '/api/zhihu-login';
});
